# Generated by Django 5.1.2 on 2024-10-23 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_of_transactions', models.DateTimeField(auto_now_add=True)),
                ('burning_coins', models.IntegerField(verbose_name='сгорание монет')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_coins', to=settings.AUTH_USER_MODEL, verbose_name='получатель монет')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_coins', to=settings.AUTH_USER_MODEL, verbose_name='передача монет')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'монеты',
            },
        ),
    ]
