# Generated by Django 5.1.2 on 2024-10-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_coins_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='title',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
