# Generated by Django 5.1.2 on 2024-10-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_alter_coins_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coins',
            name='burning_coins',
        ),
    ]
